---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - vendor/**/*

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/MissingCopEnableDirective:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
