---
name: CI
on:
  push:
    tags: ['v*']
    branches: [master]
  pull_request:
    branches: ['**']
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, jruby-9.2.19, truffleruby-21.1.0]
        bundler: [default]
        include:
          - ruby: '2.3'
            bundler: '1'
          - ruby: '2.4'
            bundler: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        env:
          REDIS_VERSION: ${{ matrix.redis }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - run: bundle exec rubocop
        if: matrix.ruby == '2.7'
      - name: start MySQL
        run: sudo /etc/init.d/mysql start
      - run: bundle exec rspec --format doc
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      - uses: codecov/codecov-action@v3
        if: matrix.ruby == '2.7'
        with:
          files: coverage/coverage.xml
      - run: bin/check-version

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
